<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.1.81</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="changelog.html" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="changelog.html" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Specification\Specification.csproj" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet &quot;..\verser\verser.dll&quot; --append &quot;..\sltlang\sltlang.csproj&quot;" />
  </Target>
</Project>