<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="samples\expr.slt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="samples\*" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="SLThree" Version="0.9.0-alpha.1014" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sltlang.Domain\sltlang.Domain.csproj" />
    <ProjectReference Include="..\Specification\Specification.csproj" />
  </ItemGroup>

</Project>
